import React from 'react'

import Layout from '../components/layout/'
import Header from '../components/header'
import FilterBar from '../components/filterBar'
import ListItem from '../components/listItem'
import ContextProvider from '../context/context'
import dropdownfilterData from '../utils/dropdownFilterData'
import { useRouter } from 'next/router'
import Head from 'next/head'


const Home = ({ transactions }) => {
  const router = useRouter()
  const { filter } = router.query;

  return (
    <>
      <Head>
        <title>Pol Challenge</title>
        <meta name="List- Home" content="Generated by Pol" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContextProvider>
        <Layout>
          <Header />
          <FilterBar transactions={transactions} filter={filter} dropdownfilterData={dropdownfilterData}/>
          <ListItem />
        </Layout>
      </ContextProvider>
    </>
  )
}

export default Home